<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="714" started-at="2017-10-10T05:37:15Z" finished-at="2017-10-10T05:37:16Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="714" started-at="2017-10-10T05:37:15Z" finished-at="2017-10-10T05:37:16Z">
      <class name="exe.Arthadb_Automation">
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="DB_Details" is-config="true" duration-ms="633" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_Customer_FirstName_Check_TC001()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_Customer_FirstName_Check_TC001" duration-ms="12" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[CUSTOMERS-FirstName check is Failed at SSN=123-45-6781,123-45-6782, expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: CUSTOMERS-FirstName check is Failed at SSN=123-45-6781,123-45-6782, expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_FirstName_Check_TC001(Arthadb_Automation.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customer_FirstName_Check_TC001 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="DB_Details" is-config="true" duration-ms="7" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_Customers_SSN_Check_TC002()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_Customers_SSN_Check_TC002" duration-ms="4" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customers_SSN_Check_TC002 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="DB_Details" is-config="true" duration-ms="7" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_PrimaryPhoneNumber_TC003()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_PrimaryPhoneNumber_TC003" duration-ms="4" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Customer - PrimaryPhoneNumber check is Failed at SSN=123-45-6781, expected:<0> but was:<1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Customer - PrimaryPhoneNumber check is Failed at SSN=123-45-6781, expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_PrimaryPhoneNumber_TC003(Arthadb_Automation.java:161)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_PrimaryPhoneNumber_TC003 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="DB_Details" is-config="true" duration-ms="7" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="PASS" signature="ArthaDB_MailingAddressZipCode_Check_TC004()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_MailingAddressZipCode_Check_TC004" duration-ms="2" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_MailingAddressZipCode_Check_TC004 -->
        <test-method status="PASS" signature="DB_Details()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="DB_Details" is-config="true" duration-ms="5" started-at="2017-10-10T11:07:15Z" finished-at="2017-10-10T11:07:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DB_Details -->
        <test-method status="FAIL" signature="ArthaDB_Customer_LastName_Check_TC005()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_Customer_LastName_Check_TC005" duration-ms="2" started-at="2017-10-10T11:07:16Z" finished-at="2017-10-10T11:07:16Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[CUSTOMERS-LastName check is Failed at SSN=123-45-6783,123-45-6784, expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: CUSTOMERS-LastName check is Failed at SSN=123-45-6783,123-45-6784, expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_LastName_Check_TC005(Arthadb_Automation.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customer_LastName_Check_TC005 -->
      </class> <!-- exe.Arthadb_Automation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
