<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
    <line>
      <![CDATA[Driver Loaded and Registered Successfully]]>
    </line>
    <line>
      <![CDATA[Connection Established with Database Successfully]]>
    </line>
    <line>
      <![CDATA[Statement Object Created Successfully]]>
    </line>
    <line>
      <![CDATA[FirstName Check Query Executeed /]]>
    </line>
    <line>
      <![CDATA[CUSTOMERS FirstName check is Failed]]>
    </line>
    <line>
      <![CDATA[Customers SSN Check Query Executeed /]]>
    </line>
    <line>
      <![CDATA[CUSTOMERS SSN check is Passed]]>
    </line>
    <line>
      <![CDATA[PrimaryPhoneNumber Check Query Executeed /]]>
    </line>
    <line>
      <![CDATA[Customer PrimaryPhoneNumber check is Failed]]>
    </line>
    <line>
      <![CDATA[Customer LastName Check Query Executeed /]]>
    </line>
    <line>
      <![CDATA[CUSTOMERS LastName check is Passed]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="731" started-at="2017-10-10T10:49:54Z" finished-at="2017-10-10T10:49:55Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="731" started-at="2017-10-10T10:49:54Z" finished-at="2017-10-10T10:49:55Z">
      <class name="exe.Arthadb_Automation">
        <test-method status="PASS" signature="getDatabaseConnection()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="getDatabaseConnection" is-config="true" duration-ms="678" started-at="2017-10-10T16:19:55Z" finished-at="2017-10-10T16:19:55Z">
          <reporter-output>
            <line>
              <![CDATA[Driver Loaded and Registered Successfully]]>
            </line>
            <line>
              <![CDATA[Connection Established with Database Successfully]]>
            </line>
            <line>
              <![CDATA[Statement Object Created Successfully]]>
            </line>
          </reporter-output>
        </test-method> <!-- getDatabaseConnection -->
        <test-method status="FAIL" signature="ArthaDB_Customer_FirstName_Check_TC001()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_Customer_FirstName_Check_TC001" duration-ms="14" started-at="2017-10-10T16:19:55Z" finished-at="2017-10-10T16:19:55Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[CUSTOMERS FirstName check is Failed at SSN=123-45-6781,123-45-6782, expected:<0> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: CUSTOMERS FirstName check is Failed at SSN=123-45-6781,123-45-6782, expected:<0> but was:<2>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_Customer_FirstName_Check_TC001(Arthadb_Automation.java:97)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[FirstName Check Query Executeed /]]>
            </line>
            <line>
              <![CDATA[CUSTOMERS FirstName check is Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customer_FirstName_Check_TC001 -->
        <test-method status="PASS" signature="ArthaDB_Customers_SSN_Check_TC002()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_Customers_SSN_Check_TC002" duration-ms="5" started-at="2017-10-10T16:19:55Z" finished-at="2017-10-10T16:19:55Z">
          <reporter-output>
            <line>
              <![CDATA[Customers SSN Check Query Executeed /]]>
            </line>
            <line>
              <![CDATA[CUSTOMERS SSN check is Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customers_SSN_Check_TC002 -->
        <test-method status="FAIL" signature="ArthaDB_PrimaryPhoneNumber_TC003()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_PrimaryPhoneNumber_TC003" duration-ms="3" started-at="2017-10-10T16:19:55Z" finished-at="2017-10-10T16:19:55Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[Customer PrimaryPhoneNumber check is Failed at SSN=123-45-6781, expected:<0> but was:<1>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: Customer PrimaryPhoneNumber check is Failed at SSN=123-45-6781, expected:<0> but was:<1>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.Assert.assertEquals(Assert.java:234)
	at exe.Arthadb_Automation.ArthaDB_PrimaryPhoneNumber_TC003(Arthadb_Automation.java:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
            <line>
              <![CDATA[PrimaryPhoneNumber Check Query Executeed /]]>
            </line>
            <line>
              <![CDATA[Customer PrimaryPhoneNumber check is Failed]]>
            </line>
          </reporter-output>
        </test-method> <!-- ArthaDB_PrimaryPhoneNumber_TC003 -->
        <test-method status="PASS" signature="ArthaDB_Customer_LastName_Check_TC004()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="ArthaDB_Customer_LastName_Check_TC004" duration-ms="3" started-at="2017-10-10T16:19:55Z" finished-at="2017-10-10T16:19:55Z">
          <reporter-output>
            <line>
              <![CDATA[Customer LastName Check Query Executeed /]]>
            </line>
            <line>
              <![CDATA[CUSTOMERS LastName check is Passed]]>
            </line>
          </reporter-output>
        </test-method> <!-- ArthaDB_Customer_LastName_Check_TC004 -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:exe.Arthadb_Automation@475530b9]" name="tearDown" is-config="true" duration-ms="2" started-at="2017-10-10T16:19:55Z" finished-at="2017-10-10T16:19:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- exe.Arthadb_Automation -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
